[package]
name = "devtools"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["debug"] }
tracing-subscriber = "0.3.18"
uuid = { version = "1.10.0", features = ["v4", "v7"] }
